import type { Metadata } from 'next';
import { Shield } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Conditions Générales d\'Utilisation',
};

const sections = [
  {
    title: '1. Présentation et champ d\'application',
    content: `Les présentes Conditions Générales d'Utilisation (ci-après "CGU") régissent l'accès et l'utilisation de la plateforme Nexus Invest, accessible depuis le site web https://nexusinvest.com ainsi que ses applications mobiles et extensions (ci-après la "Plateforme"). La Plateforme est éditée par Nexus Invest SARL, société de droit ivoirien immatriculée au RCCM d'Abidjan sous le numéro CI-ABJ-2026-B-12345, dont le siège social est situé à Abidjan, Cocody, Côte d'Ivoire. En accédant à la Plateforme, en créant un compte ou en utilisant l'un des services proposés, l'Utilisateur reconnaît avoir pris connaissance des présentes CGU et les accepter sans réserve. Les présentes CGU s'appliquent à tous les Utilisateurs de la Plateforme, qu'ils soient des personnes physiques ou morales, sans distinction. Nexus Invest se réserve le droit de modifier les présentes CGU à tout moment, les modifications prenant effet dès leur publication en ligne. Il est de la responsabilité de l'Utilisateur de consulter régulièrement les CGU. En cas de désaccord avec les CGU, l'Utilisateur doit cesser immédiatement d'utiliser la Plateforme et procéder à la suppression de son compte.`,
  },
  {
    title: '2. Définitions',
    content: [
      '"Plateforme" : désigne le site web Nexus Invest, l\'ensemble de ses fonctionnalités, interfaces, API, applications mobiles et services associés.',
      '"Utilisateur" : toute personne physique majeure (18 ans ou plus) inscrite sur la Plateforme, disposant de la capacité juridique nécessaire.',
      '"Visiteur" : toute personne accédant à la Plateforme sans y être inscrite.',
      '"Compte" : espace personnel sécurisé de l\'Utilisateur lui permettant d\'accéder aux services de la Plateforme.',
      '"Pack" : produit d\'investissement proposé sur la Plateforme avec un montant minimum, une durée et un rendement définis.',
      '"Solde" : montant disponible sur le compte de l\'Utilisateur, exprimé en FCFA, comprenant le capital investi et les gains générés.',
      '"Minage virtuel" : mécanisme de génération de revenus passifs basé sur la validation quotidienne via la Plateforme.',
      '"Parrainage" : système de référencement permettant à un Utilisateur de recommander la Plateforme à de nouveaux utilisateurs.',
      '"Données personnelles" : toute information se rapportant à une personne physique identifiée ou identifiable conformément au RGPD.',
      '"RGPD" : Règlement Général sur la Protection des Données (UE) 2016/679 du Parlement européen et du Conseil du 27 avril 2016.',
    ],
  },
  {
    title: '3. Accès au service et éligibilité',
    content: `L'accès à la Plateforme est ouvert à toute personne physique majeure (18 ans ou plus) disposant de la capacité juridique nécessaire pour contracter. L'inscription est gratuite et nécessite la fourniture d'informations exactes, complètes et à jour. En s'inscrivant, l'Utilisateur certifie sur l'honneur que toutes les informations fournies sont exactes et sincères. Nexus Invest se réserve le droit de vérifier l'exactitude des informations fournies et de demander tout justificatif nécessaire. En cas de fausse déclaration, Nexus Invest se réserve le droit de suspendre ou supprimer le compte de l'Utilisateur sans préavis ni indemnité. L'accès à certains services peut être soumis à des conditions supplémentaires (vérification d'identité, KYC, justificatif de domicile). Nexus Invest se réserve le droit de refuser l'accès à la Plateforme à tout Utilisateur ne respectant pas les présentes CGU, sans avoir à justifier sa décision.`,
  },
  {
    title: '4. Inscription et création de compte',
    content: `Lors de l'inscription, l'Utilisateur s'engage à fournir des informations exactes et complètes, notamment : nom, prénom, adresse email valide, numéro de téléphone, pays de résidence, code de parrainage le cas échéant. L'Utilisateur est tenu de créer un mot de passe sécurisé répondant aux exigences suivantes : minimum 8 caractères, au moins une majuscule, au moins une minuscule, au moins un chiffre. Le compte est strictement personnel et non cessible. L'Utilisateur est seul responsable de la confidentialité de ses identifiants de connexion. Toute activité réalisée depuis le compte est réputée émaner de l'Utilisateur. En cas d'utilisation frauduleuse ou non autorisée, l'Utilisateur doit en informer immédiatement le support technique à support@nexusinvest.com. Nexus Invest décline toute responsabilité en cas d'accès non autorisé au compte résultant d'une négligence de l'Utilisateur. Un même Utilisateur ne peut détenir qu'un seul compte. Tout compte multiple sera supprimé sans préavis.`,
  },
  {
    title: '5. Collecte et traitement des données personnelles',
    content: `Dans le cadre de l'utilisation de la Plateforme, Nexus Invest collecte et traite les données personnelles suivantes : (a) données d'identification : nom, prénom, adresse email, numéro de téléphone, adresse postale, date de naissance, pays de résidence, pièce d'identité (le cas échéant pour le KYC) ; (b) données de connexion : adresse IP, type de navigateur, système d'exploitation, pages visitées, durée de session, en-têtes HTTP, empreinte numérique de l'appareil ; (c) données financières : historique des transactions, montants investis, gains réalisés, retraits effectués, soldes des comptes, méthodes de paiement utilisées ; (d) données de parrainage : code de parrainage, nombre de filleuls, bonus générés, arbre de parrainage ; (e) données d'utilisation : préférences de compte, langue choisie, devise sélectionnée, thème d'interface, historique de navigation sur la Plateforme ; (f) données de communication : messages échangés via le système de chat, tickets de support, correspondance email. Le traitement de ces données repose sur les bases légales suivantes : (i) l'exécution du contrat d'utilisation liant l'Utilisateur à Nexus Invest ; (ii) le consentement exprès de l'Utilisateur pour les cookies non essentiels et les communications marketing ; (iii) l'obligation légale de conservation des données financières et fiscales ; (iv) l'intérêt légitime de Nexus Invest à prévenir la fraude, sécuriser la Plateforme et améliorer ses services. Les données sont conservées pendant toute la durée de validité du compte actif. Après la fermeture du compte ou après 3 ans d'inactivité, les données sont archivées pendant 3 ans supplémentaires à des fins probatoires. Les données financières sont conservées 10 ans conformément aux obligations comptables et fiscales. Pour plus d'informations sur vos droits et l'exercice de ceux-ci, consultez notre Politique de Confidentialité accessible à la page /confidentialite.`,
  },
  {
    title: '6. Services financiers et investissements',
    content: `Nexus Invest propose des packs d'investissement avec des durées et rendements variables. Chaque pack est défini par un montant minimum d'investissement, une durée exprimée en jours, un pourcentage de rendement (ROI), et un pourcentage de bonus de fidélité. Les investissements sont effectués en FCFA via Mobile Money (Orange Money, MTN Money, Moov Money), virement bancaire, ou carte bancaire (Stripe). L'Utilisateur reconnaît et accepte que : (a) le capital investi est bloqué pour la durée du pack et ne peut être récupéré avant l'échéance ; (b) les rendements sont crédités automatiquement sur le solde de l'Utilisateur selon la périodicité définie (généralement hebdomadaire) ; (c) les performances passées ne constituent pas une garantie de résultats futurs ; (d) l'investissement comporte un risque de perte partiel ou total du capital investi ; (e) Nexus Invest ne fournit aucun conseil financier personnalisé ; (f) l'Utilisateur est seul responsable de ses décisions d'investissement. Les retraits sont soumis aux conditions suivantes : montant minimum de 5 000 FCFA, traitement sous 24 à 72 heures ouvrées, frais de retrait applicables selon le mode de retrait choisi. L'Utilisateur reconnaît que les retraits peuvent être soumis à des contrôles de sécurité et de conformité (lutte anti-blanchiment, financement du terrorisme).`,
  },
  {
    title: '7. Minage virtuel',
    content: `Le minage virtuel est un mécanisme de génération de revenus passifs accessible à tous les Utilisateurs disposant d'un solde minimum requis. Le principe est le suivant : l'Utilisateur valide quotidiennement sa session de minage via un bouton dédié sur la Plateforme. Chaque validation quotidienne génère un gain en tokens NEX, calculé selon un taux défini par Nexus Invest et susceptible d'évoluer. L'Utilisateur peut cumuler des jours consécutifs de minage (streak), chaque jour supplémentaire augmentant le taux de génération. En cas d'oubli de validation un jour donné, la série est réinitialisée. Les gains accumulés peuvent être convertis en FCFA disponibles sur le solde de l'Utilisateur, selon un taux de conversion défini par Nexus Invest. Nexus Invest se réserve le droit de modifier, suspendre ou arrêter le mécanisme de minage virtuel à tout moment, sans préavis ni indemnité. L'Utilisateur reconnaît que le minage virtuel ne constitue pas une activité de minage de cryptomonnaies réelles et que les tokens NEX n'ont aucune valeur en dehors de la Plateforme.`,
  },
  {
    title: '8. Système de parrainage',
    content: `Le système de parrainage permet à l'Utilisateur (le "Parrain") de recommander la Plateforme à de nouveaux utilisateurs (les "Filleuls"). Le Parrain génère un code de parrainage unique accessible depuis son espace personnel. Lorsqu'un nouvel Utilisateur s'inscrit en utilisant ce code, le Parrain perçoit une commission calculée selon la structure suivante : (a) niveau 1 (filleuls directs) : pourcentage défini sur les investissements réalisés ; (b) niveau 2 (filleuls des filleuls) : pourcentage inférieur au niveau 1 ; (c) niveau 3 : pourcentage marginal. Les bonus de parrainage sont crédités automatiquement sur le solde du Parrain après validation de l'investissement du Filleul. Le Parrain reconnaît et accepte que : (i) le parrainage n'est pas un droit et peut être révoqué en cas d'activité frauduleuse ; (ii) le Parrain s'interdit de faire de la publicité mensongère ou d'utiliser des méthodes de recrutement agressives ; (iii) le Parrain est responsable de ses actions de promotion ; (iv) Nexus Invest se réserve le droit de modifier les taux de commission à tout moment.`,
  },
  {
    title: '9. Obligations de l\'Utilisateur',
    content: `L'Utilisateur s'engage à : (a) fournir des informations exactes et à jour ; (b) respecter les présentes CGU et la législation applicable ; (c) ne pas utiliser la Plateforme à des fins frauduleuses, illicites ou contraires à l'ordre public ; (d) ne pas tenter de contourner les mesures de sécurité de la Plateforme ; (e) ne pas créer de comptes multiples ; (f) ne pas utiliser de robots, scripts ou autres moyens automatisés pour interagir avec la Plateforme ; (g) ne pas perturber le fonctionnement de la Plateforme ; (h) ne pas diffuser de contenu injurieux, diffamatoire, raciste, xénophobe ou contraire aux bonnes mœurs ; (i) ne pas tenter de décompiler, désassembler, décrypter ou ingénierie inverse du code source ; (j) ne pas utiliser la Plateforme pour blanchir de l'argent ou financer des activités illégales ; (k) informer immédiatement Nexus Invest de toute faille de sécurité constatée ; (l) respecter les droits de propriété intellectuelle de Nexus Invest et des tiers. Tout manquement à ces obligations expose l'Utilisateur à la suspension ou suppression de son compte, sans préjudice des poursuites judiciaires éventuelles.`,
  },
  {
    title: '10. Responsabilités et garanties',
    content: `Nexus Invest met en œuvre tous les moyens techniques raisonnables pour assurer le bon fonctionnement, la sécurité et la disponibilité de la Plateforme. La Plateforme est fournie "en l'état" sans garantie expresse ou implicite. Nexus Invest ne garantit pas que la Plateforme sera exempte d'erreurs, de virus, d'interruptions ou d'autres problèmes. La responsabilité de Nexus Invest ne saurait être engagée en cas de : (i) interruption du service due à des opérations de maintenance, programmée ou d'urgence ; (ii) cas de force majeure tels que définis par la jurisprudence ivoirienne et le droit OHADA ; (iii) actes de tiers, notamment les attaques informatiques, piratages, dénis de service ; (iv) dommages indirects, pertes de profits, pertes de données, préjudice commercial ; (v) utilisation non conforme de la Plateforme par l'Utilisateur ; (vi) inexactitude des informations fournies par l'Utilisateur ; (vii) décisions d'investissement prises par l'Utilisateur. La responsabilité de Nexus Invest est limitée au montant total des frais et commissions perçus auprès de l'Utilisateur au cours des 12 mois précédant le sinistre. L'Utilisateur reconnaît et accepte ces limitations de responsabilité.`,
  },
  {
    title: '11. Propriété intellectuelle',
    content: `L'ensemble des contenus de la Plateforme, incluant mais sans s'y limiter : les textes, articles, descriptions, logos, marques déposées et non déposées, designs, interfaces utilisateur, codes sources, codes objets, bases de données, charte graphique, photographies, vidéos, animations, sons, icônes, et tout autre élément visuel ou sonore, est la propriété exclusive de Nexus Invest SARL ou de ses partenaires et concédants de licence. La marque "Nexus Invest", le logo associé, les noms de domaine nexusinvest.com et derivés, sont des marques déposées protégées par le droit ivoirien, le droit OHADA et le droit international. Toute reproduction, représentation, modification, adaptation, exploitation, traduction, distribution, téléchargement, affichage, vente, concession de sous-licence, transfert ou mise à disposition à des tiers, de tout ou partie de la Plateforme, sous quelque forme que ce soit, sans l'autorisation écrite et préalable de Nexus Invest SARL, est strictement interdite et constitutive de contrefaçon, passible de poursuites civiles et pénales conformément aux lois ivoiriennes et aux conventions internationales. L'Utilisateur bénéficie d'une licence non exclusive, non transférable et révocable à tout moment pour utiliser la Plateforme conformément aux présentes CGU. Cette licence ne confère aucun droit de propriété intellectuelle sur la Plateforme.`,
  },
  {
    title: '12. Sécurité et confidentialité',
    content: `Nexus Invest met en œuvre des mesures techniques et organisationnelles conformes à l'état de l'art pour protéger les données et transactions contre tout accès non autorisé, altération, divulgation ou destruction. Ces mesures incluent : (a) chiffrement SSL/TLS (HTTPS) pour toutes les communications entre le navigateur et les serveurs ; (b) chiffrement AES-256 pour les données sensibles au repos ; (c) authentification à deux facteurs (2FA) en option pour les comptes ; (d) tokens d'authentification avec expiration (Sanctum, 7 jours) ; (e) pare-feu applicatif (WAF) et système de détection d'intrusion (IDS) ; (f) isolation des environnements de production, développement et test ; (g) audits de sécurité réguliers et tests d'intrusion ; (h) gestion des accès basée sur le principe du moindre privilège ; (i) journalisation des accès et des actions sensibles (audit trail) ; (j) sauvegardes chiffrées avec rétention de 30 jours ; (k) plan de continuité d'activité et de reprise après sinistre. Malgré ces mesures, Nexus Invest ne peut garantir une sécurité absolue sur Internet. L'Utilisateur est invité à prendre toutes les précautions nécessaires pour protéger ses propres équipements et données. En cas de violation de données susceptible d'engendrer un risque élevé pour les droits et libertés des Utilisateurs, Nexus Invest s'engage à notifier les personnes concernées et les autorités compétentes dans les 72 heures conformément au RGPD.`,
  },
  {
    title: '13. Suspension et résiliation',
    content: `Nexus Invest se réserve le droit de suspendre ou résilier un compte Utilisateur à tout moment, sans préavis ni indemnité, en cas de : (a) violation des présentes CGU ; (b) suspicion d'activité frauduleuse ou illicite ; (c) demande d'une autorité judiciaire ou administrative ; (d) inactivité prolongée du compte (plus de 12 mois consécutifs) ; (e) défaut de fourniture des documents justificatifs requis (KYC) ; (f) comportement abusif ou nuisible envers la Plateforme, les autres Utilisateurs ou l'équipe Nexus Invest. L'Utilisateur peut à tout moment résilier son compte en adressant une demande à support@nexusinvest.com ou via la fonctionnalité dédiée dans son espace personnel. La résiliation du compte entraîne : (i) la désactivation de l'accès à la Plateforme ; (ii) la suppression des tokens d'authentification ; (iii) le remboursement du solde disponible (hors investissements en cours) sous réserve des conditions de retrait ; (iv) la conservation des données conformément à la politique de conservation en vigueur. Les investissements en cours au moment de la résiliation restent soumis aux conditions du pack souscrit et seront liquidés à leur échéance normale.`,
  },
  {
    title: '14. Données personnelles et RGPD - Dispositions détaillées',
    content: `Nexus Invest SARL, en qualité de responsable de traitement, collecte et traite les données à caractère personnel des Utilisateurs conformément au Règlement Général sur la Protection des Données (RGPD) (UE) 2016/679 et à la loi n°2013-450 du 19 juin 2013 relative à la protection des données à caractère personnel en Côte d'Ivoire. Le Délégué à la Protection des Données (DPO) de Nexus Invest peut être contacté à l'adresse dpo@nexusinvest.com. Les catégories de données collectées sont détaillées à l'article 5 des présentes CGU. Les finalités du traitement sont : gestion des comptes, exécution des contrats d'investissement, prévention de la fraude, respect des obligations légales, communication commerciale (avec consentement), amélioration des services, et réalisation de statistiques. La base légale de chaque traitement est : (a) l'exécution du contrat pour les traitements nécessaires à la fourniture des services ; (b) le consentement pour les cookies non essentiels, la géolocalisation et les communications marketing ; (c) l'obligation légale pour la conservation des données financières et fiscales ; (d) l'intérêt légitime pour la prévention de la fraude, la sécurisation de la Plateforme et l'amélioration des services. Destinataires des données : les données sont traitées par le personnel habilité de Nexus Invest et peuvent être communiquées à des sous-traitants techniques (hébergement Scaleway, services de paiement Stripe/Flutterwave, service d'envoi d'emails SendGrid) dans le cadre strict de l'exécution des services. Ces sous-traitants sont contractuellement tenus de respecter la confidentialité et la sécurité des données. Aucun transfert de données hors de l'Union Européenne n'est effectué sans garanties appropriées (clauses contractuelles types, décision d'adéquation). Durées de conservation détaillées : (i) données de compte : durée de vie du compte + 3 ans ; (ii) données financières et transactions : 10 ans (obligation comptable) ; (iii) logs de connexion et données techniques : 1 an ; (iv) données de cookies : 13 mois maximum ; (v) données KYC et pièces d'identité : 5 ans après la clôture du compte ; (vi) communications support : 3 ans. L'Utilisateur dispose des droits suivants : droit d'accès (article 15 RGPD), droit de rectification (article 16), droit à l'effacement (article 17, sous réserve des obligations légales de conservation), droit à la limitation du traitement (article 18), droit à la portabilité des données (article 20), droit d'opposition (article 21). Ces droits peuvent être exercés à tout moment via la page /confidentialite ou par email à dpo@nexusinvest.com. Nexus Invest s'engage à répondre à toute demande dans un délai maximum d'un mois (prolongeable à deux mois en cas de complexité). En cas de réclamation non résolue, l'Utilisateur peut saisir la Commission Nationale de l'Informatique et des Libertés (CNIL) ou l'autorité de protection des données compétente de son pays.`,
  },
  {
    title: '15. Cookies et technologies de suivi',
    content: `La Plateforme utilise des cookies et technologies similaires (localStorage, sessionStorage, tokens) pour assurer son fonctionnement, améliorer l'expérience utilisateur et réaliser des statistiques d'audience. Un cookie est un petit fichier texte déposé sur le terminal de l'Utilisateur lors de la visite de la Plateforme. Les cookies utilisés sont : (A) Cookies strictement nécessaires (obligatoires) : cookie de session Laravel, XSRF-TOKEN pour la protection contre les attaques CSRF, token d'authentification Sanctum, identifiant de session. Ces cookies sont essentiels au fonctionnement de la Plateforme et ne peuvent pas être désactivés. Durée : session ou 24 heures. (B) Cookies fonctionnels : préférences de thème (clair/sombre), langue sélectionnée, devise choisie. Ces cookies améliorent l'expérience utilisateur. Durée : 1 an. (C) Cookies analytiques et de performance : mesures d'audience, pages les plus visitées, parcours utilisateur, taux de conversion, temps de chargement. Ces données sont anonymisées et utilisées uniquement pour améliorer la Plateforme. Durée : 13 mois. (D) Cookies tiers : Google reCAPTCHA (protection anti-bot), Stripe et Flutterwave (paiement), SendGrid (emails transactionnels). Ces cookies sont soumis aux politiques de confidentialité de leurs émetteurs respectifs. L'Utilisateur est informé que le dépôt de cookies non essentiels est soumis à son consentement préalable, recueilli via le bandeau d'information cookies affiché lors de la première visite. L'Utilisateur peut à tout moment configurer, modifier ou retirer son consentement via la page de gestion des cookies ou les paramètres de son navigateur. Le refus des cookies techniques empêche l'utilisation normale de la Plateforme.`,
  },
  {
    title: '16. Lutte anti-blanchiment et financement du terrorisme (LAB/FT)',
    content: `Conformément à la réglementation ivoirienne et aux recommandations du Groupe d'Action Financière (GAFI), Nexus Invest applique des mesures de vigilance à l'égard de ses Utilisateurs. Ces mesures incluent : (a) vérification de l'identité des Utilisateurs (KYC) pour les transactions au-delà d'un seuil défini ; (b) conservation des documents d'identité et justificatifs de domicile ; (c) analyse des transactions suspectes ; (d) déclaration aux autorités compétentes (CENTIF - Cellule Nationale de Traitement des Informations Financières) en cas de soupçon de blanchiment ou de financement du terrorisme ; (e) gel des avoirs sur instruction des autorités ; (f) obligation de déclaration des transactions en espèces supérieures à 5 000 000 FCFA. L'Utilisateur s'engage à : (i) fournir tous les documents justificatifs demandés dans le cadre de la LAB/FT ; (ii) informer Nexus Invest de toute modification de sa situation personnelle ; (iii) ne pas utiliser la Plateforme pour des transactions illicites. Le défaut de coopération de l'Utilisateur dans le cadre de ces obligations peut entraîner la suspension immédiate de son compte et le blocage de ses fonds jusqu'à régularisation.`,
  },
  {
    title: '17. Médiation et résolution des litiges',
    content: `En cas de litige entre l'Utilisateur et Nexus Invest, les parties conviennent de rechercher une solution amiable avant toute action judiciaire. La procédure de médiation est la suivante : (1) l'Utilisateur adresse une réclamation écrite au service client à support@nexusinvest.com ; (2) Nexus Invest accuse réception de la réclamation sous 5 jours ouvrés et y répond sous 30 jours maximum ; (3) si la réponse ne satisfait pas l'Utilisateur, celui-ci peut saisir le médiateur désigné par Nexus Invest dans un délai de 30 jours suivant la réponse ; (4) la médiation est gratuite pour l'Utilisateur ; (5) la durée de la médiation est de 60 jours maximum, renouvelable une fois. À défaut d'accord amiable, les tribunaux compétents sont ceux d'Abidjan (Côte d'Ivoire), et le droit applicable est le droit ivoirien, complété par le droit OHADA et le droit de l'Union Européenne pour les dispositions relatives à la protection des données. Pour les Utilisateurs résidant dans l'Union Européenne, la plateforme de règlement en ligne des litiges (RLL) est accessible à l'adresse https://ec.europa.eu/consumers/odr/.`,
  },
  {
    title: '18. Dispositions diverses',
    content: `(a) Nullité partielle : si une disposition des présentes CGU est déclarée nulle ou inapplicable par une juridiction compétente, les autres dispositions restent en vigueur. (b) Non-renonciation : le fait pour Nexus Invest de ne pas se prévaloir d'un manquement aux CGU ne constitue pas une renonciation à s'en prévaloir ultérieurement. (c) Intégralité : les présentes CGU, la Politique de Confidentialité et les Mentions Légales constituent l'intégralité de l'accord entre l'Utilisateur et Nexus Invest. (d) Langue : en cas de traduction des CGU, la version française fait foi. (e) Force majeure : les parties ne peuvent être tenues responsables en cas de force majeure telle que définie par l'article 10 de l'Acte Uniforme OHADA portant sur le droit des obligations. (f) Cession : l'Utilisateur ne peut céder ses droits et obligations au titre des présentes CGU sans l'accord écrit préalable de Nexus Invest. Nexus Invest peut librement céder tout ou partie de ses droits et obligations dans le cadre d'une fusion, acquisition ou restructuration. (g) Informations nominatives : l'Utilisateur est informé que ses données personnelles font l'objet d'un traitement automatisé, comme détaillé à l'article 14 des présentes CGU et dans la Politique de Confidentialité.`,
  },
  {
    title: '19. Contact et information',
    content: `Pour toute question relative aux présentes CGU, à l'utilisation de la Plateforme, à vos droits en matière de protection des données, ou pour toute réclamation, vous pouvez contacter Nexus Invest aux coordonnées suivantes : Email support : support@nexusinvest.com, Email DPO : dpo@nexusinvest.com, Email juridique : legal@nexusinvest.com, Téléphone : +225 01 02 03 04 05, Adresse postale : Nexus Invest SARL, 01 BP 1234 Abidjan 01, Côte d'Ivoire. Horaires du support : du lundi au vendredi de 08h00 à 18h00 (UTC+0). Nous nous engageons à répondre à toute demande dans un délai maximum de 48 heures ouvrées pour les questions générales, et d'un mois pour les demandes relatives aux données personnelles.`,
  },
];

function SectionCard({ title, content }: { title: string; content: string | string[] }) {
  return (
    <div className="rounded-2xl bg-white/70 dark:bg-slate-900/70 border border-white/20 dark:border-slate-700/30 backdrop-blur-xl p-6 md:p-8 shadow-md">
      <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-4">{title}</h2>
      {Array.isArray(content) ? (
        <ul className="space-y-2">
          {content.map((item, i) => (
            <li key={i} className="text-sm text-slate-600 dark:text-slate-400 flex gap-2">
              <span className="text-emerald-500 mt-1.5 h-1.5 w-1.5 rounded-full bg-emerald-500 shrink-0" />
              <span>{item}</span>
            </li>
          ))}
        </ul>
      ) : (
        <p className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed whitespace-pre-line">{content}</p>
      )}
    </div>
  );
}

export default function CguPage() {
  return (
    <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8 py-12 md:py-16">
      <div className="flex items-center gap-3 mb-2">
        <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-emerald-500 to-emerald-600">
          <Shield className="h-5 w-5 text-white" />
        </div>
        <h1 className="text-3xl md:text-4xl font-extrabold text-slate-900 dark:text-white">
          Conditions Générales d&rsquo;Utilisation
        </h1>
      </div>
      <p className="text-sm text-slate-500 dark:text-slate-400 mb-10 ml-13">
        Dernière mise à jour : 25 juillet 2026
      </p>

      <div className="space-y-6">
        {sections.map((section) => (
          <SectionCard key={section.title} title={section.title} content={section.content} />
        ))}
      </div>
    </div>
  );
}
